### ISSUE TITLE
[Discuss] Some (maybe) useful suggestions

### ISSUE THREAD

**Issue by zw963** [thiagoa/rbtagger#46]
1. Support index ruby standard library. e.g.  `Singleton` can not be retrieve in TAGS
2. seperate not live changed ruby code (gem/ruby standard library) into a seperate file, and current project tags into another one, 
    then, we can add hook to ensure latter will be updated wait several minutes, as done in  [ctags-update](https://github.com/jixiuf/ctags-update)

Thank you.

**Comment by thiagoa** [comment]
@zw963 Thank you for the suggestions!

1. I agree! We will have this implemented.
2. I think I understand what you mean. If we separate out project tags, we can update the project tags alone on a save hook. I need to play around with that and see how much faster it would be, as the script is already optimized even taking gems into account.

**Comment by thiagoa** [comment]
@zw963 The suggestions have been implemented here:

https://github.com/thiagoa/rbtagger/pull/50 - Index Ruby stdlib
https://github.com/thiagoa/rbtagger/pull/51 - Allow generating tags on after save hook. I implemented a locking mechanism to queue up runs and a snippet suggestion to setup an `after-save-hook`

I did not find it necessary to have a separate `TAGS` file for the project because the script is already smart enough to skip tags that have already been generated, so it should run fast after the first run. Let me know if it does not though.

Thank you so much for the suggestions and let me know how the features work for you!

NOTE: It is not up on MELPA yet. I think it will be in one+ hours.

**Comment by zw963** [comment]
indexing seem like works file now, though, do you meet the error when indexing some files like `.#app.rb`,  those files is file lock file create by emacs automatically. https://www.gnu.org/software/emacs/manual/html_node/elisp/File-Locks.html#File-Locks, so, i propose add ` --exclude=.#*.rb` to avoid this. sure we can disable lockfile use `(setq create-lockfiles nil)`, but, anyway, any effort which maybe avoid editing missing is worthy.


 i try add TAGS into tags-table-list manually. it works quite well. thanks for this package, but, there is a concern, i find `rbtagger-find-definitions` not works when enable `lsp`, in fact, it works when first time run `rbtagger-find-definition`, and then,
always get `no difinition found` issue. but, if use `helm-etags-select` instead, definition can always be find successful.

![image](https://user-images.githubusercontent.com/549126/138215586-1eb5facd-70f6-4113-b58a-8fc9237e8edf.png)

 That was not a big deal for me, because i use robe-mode and etags,  lsp + solargraph not so useful for me, but, this issue should be mentioned anyway.
